trigger:
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*
      
  paths:
    include:
    - '/'
    exclude:
    - .dependabot/
    - .github/
    # don't trigger the CI if only docs files are changed
    - doc/*
    - '**/*.md'
    - '*.md'
    - 'build/cSpell.json'
    
pr: 
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*
      
  paths:
    include:
    - '/'
    exclude:
    - .dependabot/
    - .github/
    # don't trigger the CI if only docs files are changed
    - doc/*
    - '**/*.md'
    - '*.md'
    - 'build/cSpell.json'

stages:
- template: build/ci/.azure-devops-stages.yml
